### ISSUE TITLE
Super Guilds wont start - Says "Outdated" (but it's not)

### ISSUE THREAD

**Issue by Tomm-yT** [RepublicanSensei/SUPERGUILDS#1]
I just purchased this plugin today and was disappointed that I have yet to even get it to work. I followed all the installation instructions yet when I try to launch it on my server, console says "This version is outdated. Download the new version from http://bit.ly/2kPLZap" despite me getting and installing the newest version possible (5.9.4).

**Comment by RepublicanSensei** [comment]
Fixed in new version! Thanks
