### ISSUE TITLE
issue when i try to use the plugin

### ISSUE THREAD

**Issue by SubZeroExtaByte** [RepublicanSensei/SUPERGUILDS#2]
i just downloaded the plugin, when i try to type any command in the chat i can't and it just say "<.none>". in the logs i just have warning cause materials ID. I'm using 1.8.8 MC version and i downloaded the Aliases-english.sk. I already tried to install different versions.

-Thanks for your help

**Comment by RepublicanSensei** [comment]
Hey, try to use ./g updatelocale or "Copy "plugins/SUPERGUILDS/locales/en_US.sk" to "plugins/Skript/scripts" folder.
