### ISSUE TITLE
Upgrade wrong chunk

### ISSUE THREAD

**Issue by Ricozaur** [RepublicanSensei/SUPERGUILDS#6]
Hello there, 2 days ago i've started using your plugin because i find that Towny has a lack of Adventure.
So i found your plugin and it seemed really nice so i bought it. So i was testing around with the buildings and such and have found an issue with the buildings upgrade.

Whenever you do an upgrade of any building the hologram and surrounding blocks will show up at the wrong chunk (it will show them in the chunk your standing on.)

Here are a couple of screenshots:

![image](https://user-images.githubusercontent.com/41333341/44257701-1ecfa780-a20d-11e8-82f7-82281b13ea4f.png)

![image](https://user-images.githubusercontent.com/41333341/44257816-766e1300-a20d-11e8-8aec-47a386b60dcc.png)

![image](https://user-images.githubusercontent.com/41333341/44257823-7cfc8a80-a20d-11e8-810a-f0135545b58b.png)

**Comment by RepublicanSensei** [comment]
Fixed in new version, thanks!
