### ISSUE TITLE
Players won't teleport back to previous location or spawn after the war.

### ISSUE THREAD

**Issue by Ricozaur** [RepublicanSensei/SUPERGUILDS#7]
Whenever the last 2 players standing are fighting and 1 wins the person doesn't die they both get stuck in the war arena and have to do /spawn or /warps to get out.

Would you mind adding a feature like "Kill on death" and "Teleport back to previous location/spawn"

Thanks in advance! :D

- Ricardo

**Comment by RepublicanSensei** [comment]
It'll teleport players to previous location in new version, thanks!
