### ISSUE TITLE
Request!

### ISSUE THREAD

**Issue by Ricozaur** [RepublicanSensei/SUPERGUILDS#8]
Hey there! i've gotten quite a liking to your SuperGuilds plugin. It has alot of Adventure in it and that's exactly what i needed. But i would like some more economy and privacy to the plugin by adding per guild member plots and for rent they will pay resources (donate to guild) or money (in a guild bank or in the leaders wallet). I think players would love to own their own piece of land to build on.
I think this would be a really nice feature.

Thank you for reading!

:D

**Comment by RepublicanSensei** [comment]
I don't really want to merge economy with guilds. Thanks

**Comment by Ricozaur** [comment]
Oh that's no problem then, thanks for replying.
