### ISSUE TITLE
N/A Problem

### ISSUE THREAD

**Issue by Ricozaur** [RepublicanSensei/SUPERGUILDS#9]
Heyo, whenever a new player joins their placeholder will tell them N/A instead of No Guild.
The annoying part is the emblem placeholders saying N/A over and over.

New player:
False:
![image](https://user-images.githubusercontent.com/41333341/44352128-cbc35200-a4a3-11e8-903a-35be4836e577.png)

When new player creates a guild and deletes it afterwards:
Correct:
![image](https://user-images.githubusercontent.com/41333341/44352178-f1505b80-a4a3-11e8-845a-d30e471f9aab.png)

**Comment by RepublicanSensei** [comment]
Thanks, Will be fixed!
